import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Board
 from '../components/Board'
export default function Home() {


  const [mines,setMines] = useState([true,false,false,false,true,false,false,false,false])
  const [gridSize,setGridSize] = useState(9)
  const [numberOfMines,setNumberOfMines] = useState(2)

  function makeGame(gridSize,numberOfMines){
    let minePositions = [];
    while (minePositions.length < numberOfMines){
      let position = Math.floor(Math.random()*gridSize)
      if(!minePositions.includes(position)){
        minePositions.push(position)
      }  
    }
    let gameGrid = [];
    for (let i = 0; i < gridSize; i++){
      if (minePositions.includes(i)){
        gameGrid.push(true)
      } else {
        gameGrid.push(false)
      }
    }
    setMines(gameGrid)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Minesweeper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Board gameBoard={mines}></Board>
        <button onClick={()=>{makeGame(gridSize,numberOfMines)}}>New Game</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
